# Generated by Django 4.1.7 on 2023-03-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
